import type { SiteConfig, SiteContent } from "../types";


export const SITE_CONFIG: SiteConfig = {
  title: "Ashley Rounds - Designer",
  author: "Ashley Rounds",
  description:
    "Floral designer based in Dallas, Texas. Specializing in floral arrangements from small bouquets to grand floral scenes.",
  lang: "en",
  siteLogo: "/ashleyrounds_big.jpg",
  navLinks: [
    { text: "Experience", href: "#experience" },
    { text: "Projects", href: "#projects" },
    { text: "Gallery", href: "/gallery" },
    { text: "About", href: "#about" },
  ],
  socialLinks: [
    // { text: "Twitter", href: "https://github.com/immois/astro-zen" },
    // { text: "LinkedIn", href: "https://github.com/immois/astro-zen" },
    // { text: "Github", href: "https://github.com/immois/astro-zen" },
    // { text: "Youtube", href: "https://github.com/immois/astro-zen" },
    // { text: "Dribbble", href: "https://github.com/immois/astro-zen" },
  ],
  socialImage: "/zen-og.png",
  canonicalURL: "https://astro-zen.vercel.app",
};

export const SITE_CONTENT: SiteContent = {
  hero: {
    name: "Ashley Rounds",
    specialty: "Designer",
    summary:
      "Floral designer based in Dallas, Texas. Specializing in floral arrangements from small bouquets to grand floral scenes.",
    email: "roundsashley@gmail.com",
  },
  experience: [
    {
      company: "Ashley Rounds Designs",
      position: "Designer",
      startDate: "January 2003",
      endDate: "Present",
      summary: [
        "My experience will be described here in the near future",
      ],
    },
    // {
    //   company: "Zalmart",
    //   position: "Lead Android Developer",
    //   startDate: "May 2018",
    //   endDate: "Sept 2020",
    //   summary: [
    //     "Implemented advanced memory management and code optimization techniques, resulting in a reduction in application load time by 40% and a decrease in crashes by 25%. This significantly improved user experience and increased user retention by 20%.",
    //     "I led a team of developers in building and integrating new features using Jetpack Android components such as LiveData and ViewModel. This enabled us to build scalable and maintainable applications, reducing the crash rate by 20% and speeding up the time to delivery of new features by 15%.",
    //     "Integrated Google Pay for in-app purchases, resulting in a 35% increase in mobile transaction revenue. Additionally, implemented Firebase Analytics to gain insights into user behavior, enabling data-driven optimizations and a 30% increase in user retention.",
    //   ],
    // },
    // {
    //   company: "Bankit",
    //   position: "Mobile Developer",
    //   startDate: "Feb 2017",
    //   endDate: "May 2018",
    //   summary: [
    //     "I designed and developed a mobile application using Flutter, allowing it to be deployed on both Android and iOS with a single codebase. This reduced development time by 50% and maintenance costs by 30%, facilitating a consistent user experience on both platforms.",
    //     "I integrated biometric authentication and data encryption, significantly improving the security of user data. This implementation resulted in a 40% increase in user trust and a 25% reduction in unauthorized access attempts.",
    //   ],
    // },
    // {
    //   company: "Driveer",
    //   position: "Frontend Developer",
    //   startDate: "Jun 2015",
    //   endDate: "Oct 2016",
    //   summary:
    //     "Developed and integrated a real-time vehicle tracking system using WebSockets, improving accuracy and data update in the application. This functionality increased user satisfaction by 30% and reduced customer service inquiries by 25%.",
    // },
  ],
  // projects: [
    // {
    //   name: "Spotifu Music",
    //   summary: "A music streaming app that emulates Spotify's core features.",
    //   linkPreview: "/",
    //   linkSource: "https://github.com/immois/astro-zen",
    //   image: "/spotifu.png",
    // },
    // {
    //   name: "Shopp App",
    //   summary: "An e-commerce platform that replicates Shopify's key features.",
    //   linkPreview: "/",
    //   linkSource: "https://github.com/immois/astro-zen",
    //   image: "/shopify-clon.png",
    // },
    // {
    //   name: "ClonTagram",
    //   summary: "A social network that replicates the features of Instagram",
    //   linkPreview: "/",
    //   linkSource: "https://github.com/immois/astro-zen",
    //   image: "/clone-ig.png",
    // },
  //],
  about: {
    description: `
      Hi, I’m Ashley Rounds, a passionate floral designer with a knack for crafting beautiful floral arrangements. 
    `,
    image: "/ashleyrounds_big.jpg",
  },
  photos: [
    {
      slug: "img-0045-medium", 
      title: "Overhead Arrangement",
      image: "/IMG_0045 Medium.jpeg",
      category: "Arrangement",
      date: "April 2024",
      description: "",
    },
    {
      slug: "img-0211-medium",
      title: "Bouquet",
      image: "/IMG_0211 Medium.jpeg",
      category: "Bouquet",
      date: "April 2024",
      description: "",
    },
    {
      slug: "img-0263-medium",
      title: "Bouquet",
      image: "/IMG_0263 Medium.jpeg",
      category: "Bouquet",
      date: "April 2024",
      description: "",
    },
    {
      slug: "img-0266-medium",
      title: "Bouquet",
      image: "/IMG_0266 Medium.jpeg",
      category: "Bouquet",
      date: "April 2024",
      description: "",
    },
    {
      slug: "img-0384-medium",
      title: "Centerpiece",
      image: "/IMG_0384 Medium.jpeg",
      category: "Centerpiece",
      date: "April 2024",
      description: "",
    },
    {
      slug: "img-0386-medium",
      title: "Bouquet",
      image: "/IMG_0386 Medium.jpeg",
      category: "Bouquet",
      date: "April 2024",
      description: "",
    },
    {
      slug: "img-0407-medium",
      title: "Bouquet",
      image: "/IMG_0407 Medium.jpeg",
      category: "Bouquet",
      date: "April 2024",
      description: "",
    },
    {
      slug: "img-0603-medium",
      title: "Bouquet",
      image: "/IMG_0603 Medium.jpeg",
      category: "Bouquet",
      date: "April 2024",
      description: "",
    },
    {
      slug: "img-0605-medium",
      title: "Bouquet",
      image: "/IMG_0605 Medium.jpeg",
      category: "Bouquet",
      date: "April 2024",
      description: "",
    },
    {
      slug: "img-0608-medium",
      title: "Centerpiece",
      image: "/IMG_0608 Medium.jpeg",
      category: "Centerpiece",
      date: "April 2024",
      description: "",
    },
    {
      slug: "img-0611-medium",
      title: "Wreath",
      image: "/IMG_0611 Medium.jpeg",
      category: "Wreath",
      date: "April 2024",
      description: "",
    },
    {
      slug: "img-0672-medium",
      title: "Centerpiece",
      image: "/IMG_0672 Medium.jpeg",
      category: "Centerpiece",
      date: "April 2024",
      description: "",
    },
    {
      slug: "img-0680-medium",
      title: "Centerpiece",
      image: "/IMG_0680 Medium.jpeg",
      category: "Centerpiece",
      date: "April 2024",
      description: "",
    },
    {
      slug: "img-0703-medium",
      title: "Centerpiece",
      image: "/IMG_0703 Medium.jpeg",
      category: "Centerpiece",
      date: "April 2024",
      description: "",
    },
    {
      slug: "img-0836-medium",
      title: "Vase",
      image: "/IMG_0836 Medium.jpeg",
      category: "Vase",
      date: "April 2024",
      description: "",
    },
    {
      slug: "img-0878-medium",
      title: "Vase",
      image: "/IMG_0878 Medium.jpeg",
      category: "Vase",
      date: "April 2024",
      description: "",
    },
    {
      slug: "img-0887-medium",
      title: "Vase",
      image: "/IMG_0887 Medium.jpeg",
      category: "Vase",
      date: "April 2024",
      description: "",
    },
    {
      slug: "img-1368-medium",
      title: "Overhead Arrangement",
      image: "/IMG_1368 Medium.jpeg",
      category: "Arrangement",
      date: "April 2024",
      description: "",
    },
    {
      slug: "img-1397-medium",
      title: "Wreath",
      image: "/IMG_1397 Medium.jpeg",
      category: "Wreath",
      date: "April 2024",
      description: "",
    },
    {
      slug: "img-1404-medium",
      title: "Wreath",
      image: "/IMG_1404 Medium.jpeg",
      category: "Wreath",
      date: "April 2024",
      description: "",
    },
    {
      slug: "img-1589-medium",
      title: "Vase",
      image: "/IMG_1589 Medium.jpeg",
      category: "Vase",
      date: "April 2024",
      description: "",
    },
    {
      slug: "img-1609-medium",
      title: "Vase",
      image: "/IMG_1609 Medium.jpeg",
      category: "Vase",
      date: "April 2024",
      description: "",
    },
    {
      slug: "img-1624-medium",
      title: "Vase",
      image: "/IMG_1624 Medium.jpeg",
      category: "Vase",
      date: "April 2024",
      description: "",
    },
    {
      slug: "img-1628-medium",
      title: "Vase",
      image: "/IMG_1628 Medium.jpeg",
      category: "Vase",
      date: "April 2024",
      description: "",
    },
    {
      slug: "img-1710-medium",
      title: "Bouquet",
      image: "/IMG_1710 Medium.jpeg",
      category: "Bouquet",
      date: "April 2024",
      description: "",
    },
    {
      slug: "img-1725-medium",
      title: "Bouquet",
      image: "/IMG_1725 Medium.jpeg",
      category: "Bouquet",
      date: "April 2024",
      description: "",
    },
    {
      slug: "img-1739-medium",
      title: "Bouquet",
      image: "/IMG_1739 Medium.jpeg",
      category: "Bouquet",
      date: "April 2024",
      description: "",
    },
    {
      slug: "img-1750-medium",
      title: "Bouquet",
      image: "/IMG_1750 Medium.jpeg",
      category: "Bouquet",
      date: "April 2024",
      description: "",
    },
    {
      slug: "img-1786-medium",
      title: "Bouquet",
      image: "/IMG_1786 Medium.jpeg",
      category: "Bouquet",
      date: "April 2024",
      description: "",
    },
    {
      slug: "img-20140811-125733-medium",
      title: "Centerpiece",
      image: "/IMG_20140811_125733 Medium.jpeg",
      category: "Centerpiece",
      date: "April 2024",
      description: "",
    },
    {
      slug: "img-20150213-134040-medium",
      title: "Vase",
      image: "/IMG_20150213_134040 Medium.jpeg",
      category: "Vase",
      date: "April 2024",
      description: "",
    },
    {
      slug: "img-20180904-120623-medium",
      title: "Vase",
      image: "/IMG_20180904_120623 Medium.jpeg",
      category: "Vase",
      date: "April 2024",
      description: "",
    },
    {
      slug: "img-2113-medium",
      title: "Team Photo",
      image: "/IMG_2113 Medium.jpeg",
      category: "Gallery",
      date: "April 2024",
      description: "",
    },
    {
      slug: "img-2120-medium",
      title: "Team Photo",
      image: "/IMG_2120 Medium.jpeg",
      category: "Gallery",
      date: "April 2024",
      description: "",
    },
    {
      slug: "img-2694-medium",
      title: "Centerpiece",
      image: "/IMG_2694 Medium.jpeg",
      category: "Centerpiece",
      date: "April 2024",
      description: "",
    },
    {
      slug: "img-2711-medium",
      title: "Centerpiece",
      image: "/IMG_2711 Medium.jpeg",
      category: "Centerpiece",
      date: "April 2024",
      description: "",
    },
    {
      slug: "img-3462-medium",
      title: "Vase",
      image: "/IMG_3462 Medium.jpeg",
      category: "Vase",
      date: "April 2024",
      description: "",
    },
    {
      slug: "img-3465-medium",
      title: "Vase",
      image: "/IMG_3465 Medium.jpeg",
      category: "Vase",
      date: "April 2024",
      description: "",
    },
    {
      slug: "img-3509-medium",
      title: "Wall Arrangement",
      image: "/IMG_3509 Medium.jpeg",
      category: "Arrangement",
      date: "April 2024",
      description: "",
    },
    {
      slug: "img-3525-medium",
      title: "Team Photo",
      image: "/IMG_3525 Medium.jpeg",
      category: "Gallery",
      date: "April 2024",
      description: "",
    },
    {
      slug: "img-3528-medium",
      title: "Wall Arrangement",
      image: "/IMG_3528 Medium.jpeg",
      category: "Arrangement",
      date: "April 2024",
      description: "",
    },
    {
      slug: "img-3537-medium",
      title: "Wall Arrangement",
      image: "/IMG_3537 Medium.jpeg",
      category: "Arrangement",
      date: "April 2024",
      description: "",
    },
    {
      slug: "img-3538-medium",
      title: "Vase",
      image: "/IMG_3538 Medium.jpeg",
      category: "Vase",
      date: "April 2024",
      description: "",
    },
    {
      slug: "img-3543-medium",
      title: "Vase",
      image: "/IMG_3543 Medium.jpeg",
      category: "Vase",
      date: "April 2024",
      description: "",
    },
    {
      slug: "img-5534-medium",
      title: "Centerpiece",
      image: "/IMG_5534 Medium.jpeg",
      category: "Centerpiece",
      date: "April 2024",
      description: "",
    },
    {
      slug: "img-5539-medium",
      title: "Centerpiece",
      image: "/IMG_5539 Medium.jpeg",
      category: "Centerpiece",
      date: "April 2024",
      description: "",
    },
    {
      slug: "img-6294-medium",
      title: "Team Photo",
      image: "/IMG_6294 Medium.jpeg",
      category: "Gallery",
      date: "April 2024",
      description: "",
    },
    {
      slug: "img-6466-medium",
      title: "Vase",
      image: "/IMG_6466 Medium.jpeg",
      category: "Vase",
      date: "April 2024",
      description: "",
    },
    {
      slug: "img-6623-medium",
      title: "Vase",
      image: "/IMG_6623 Medium.jpeg",
      category: "Vase",
      date: "April 2024",
      description: "",
    },
    {
      slug: "img-6625-medium",
      title: "Vase",
      image: "/IMG_6625 Medium.jpeg",
      category: "Vase",
      date: "April 2024",
      description: "",
    },
    {
      slug: "img-6634-medium",
      title: "Vase",
      image: "/IMG_6634 Medium.jpeg",
      category: "Vase",
      date: "April 2024",
      description: "",
    },
    {
      slug: "img-6678-medium",
      title: "Vase",
      image: "/IMG_6678 Medium.jpeg",
      category: "Vase",
      date: "April 2024",
      description: "",
    },
    {
      slug: "img-6687-medium",
      title: "Vase",
      image: "/IMG_6687 Medium.jpeg",
      category: "Vase",
      date: "April 2024",
      description: "",
    },
    {
      slug: "img-6893-medium",
      title: "Bouquet",
      image: "/IMG_6893 Medium.jpeg",
      category: "Bouquet",
      date: "April 2024",
      description: "",
    },
    {
      slug: "img-6924-medium",
      title: "Bouquet",
      image: "/IMG_6924 Medium.jpeg",
      category: "Bouquet",
      date: "April 2024",
      description: "",
    },
    {
      slug: "img-6927-medium",
      title: "Bouquet",
      image: "/IMG_6927 Medium.jpeg",
      category: "Bouquet",
      date: "April 2024",
      description: "",
    },
    {
      slug: "img-6930-medium",
      title: "Bouquet",
      image: "/IMG_6930 Medium.jpeg",
      category: "Bouquet",
      date: "April 2024",
      description: "",
    },
    {
      slug: "img-6938-medium",
      title: "Bouquet",
      image: "/IMG_6938 Medium.jpeg",
      category: "Bouquet",
      date: "April 2024",
      description: "",
    },
    {
      slug: "img-7949-medium",
      title: "Vase",
      image: "/IMG_7949 Medium.jpeg",
      category: "Vase",
      date: "April 2024",
      description: "",
    },
  ],
};

// #5755ff
